search_paths = ["/home/felix/Projects"]
max_depth = 2

[session]
active = "Terminal"

[[session.windows]]
name = "Editor"
cmd = ["nvim"]

[[session.windows]]
name = "Git"
cmd = ["lazygit"]

[[session.windows]]
name = "Terminal"
path = "nix"
